export const productsData = [
  {
    image: "/Images/GRIYA CITRA BARUGA.jpg",
    title: "Griya Citra Baruga",
    desc: "Jl.KS Tubun, Baruga",
    rating: 4,
    price: "3Jt",
    hargaCoret: "Rp 5.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Griya Citra Baruga",
    linkTiktok: "https://www.tiktok.com/@adeamiri?_t=ZS-8vdLvc1hEfs&_r=1",
    linkFacebook: "https://www.facebook.com/AlenkaPropertiKendari/",
    linkDetail: "/GriyaCitraBaruga",
  },
  {
    image: "/Images/BUMI ANAWAI LAND.jpg",
    title: "Bumi Anawai Land",
    desc: "Jl.Anawai, Kel. Wua-Wua",
    rating: 4,
    price: "4Jt",
    hargaCoret: "Rp 11.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Bumi Anawai Land",
    linkTiktok: "https://vt.tiktok.com/ZSrxtbRbf/",
    linkFacebook: "https://www.facebook.com/share/v/168zCV2fsa/",
    linkDetail: "/BumiAnawaiLand",
  },
  {
    image: "/Images/GRIYA CITRA ANAWAI.jpg",
    title: "Griya Citra Anawai",
    desc: "Jl.Anawai, Kel. Wua-Wua",
    rating: 4,
    price: "6Jt",
    hargaCoret: "Rp 14.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Griya Citra Anawai",
    linkTiktok: "https://vt.tiktok.com/ZSr4QRWma/",
    linkFacebook: "https://www.facebook.com/share/r/16Rn7bLjgt/",
    linkDetail: "/GriyaCitraAnawai",
  },
  {
    image: "/Images/GRIYA CITRA WATUBANGGA.jpg",
    title: "Griya Citra Watubangga",
    desc: "Jl.Kapten Piere Tendean, Baruga",
    rating: 4,
    price: "11Jt",
    hargaCoret: "Rp 15.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Griya Citra Watubangga",
    linkTiktok: "https://vt.tiktok.com/ZSrXH4L4M/",
    linkFacebook: "https://www.facebook.com/share/r/14XK578JTX/",
    linkDetail: "/GriyaCitraWatubangga",
  },
  {
    image: "/Images/GRIYA IB HASANAH.jpg",
    title: "Griya IB Hasanah",
    desc: "Jl.Chairil Anwar, THR-Puwatu",
    rating: 4,
    price: "16Jt",
    hargaCoret: "Rp 3.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Griya IB Hasanah",
    linkTiktok: "https://vt.tiktok.com/ZSrQQBgdB/",
    linkFacebook: "https://www.facebook.com/share/v/16X2NZN1Jm/",
    linkDetail: "/GriyaIbHasanah",
  },
  {
    image: "/Images/MUTIARA ATHIRA BARUGA 2.jpg",
    title: "Mutiara Athirah Baruga 2",
    desc: "Jl.KS Tubun, Baruga",
    rating: 4,
    price: "9Jt",
    hargaCoret: "Rp 26.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Mutiara Athirah Baruga 2",
    linkTiktok: "https://vt.tiktok.com/ZSrqTfH31/",
    linkFacebook: "https://www.facebook.com/share/r/196BuNBZTu/",
    linkDetail: "/MutiaraAthiraBaruga2",
  },
  {
    image: "/Images/MUTIARA ATHIRA BARUGA 3.jpg",
    title: "Mutiara Athirah Baruga 3",
    desc: "Jl.Kapten Piere Tendean, Baruga",
    rating: 4,
    price: "46Jt",
    hargaCoret: "Rp 50.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Mutiara Athirah Baruga 3",
    linkTiktok: "https://vt.tiktok.com/ZSrxtb7b2/",
    linkFacebook: "https://www.facebook.com/share/r/1FMK76T5Jk/",
    linkDetail: "/MutiaraAthiraBaruga3",
  },

  {
    image: "/Images/PESONA KING ADHAM 2.jpg",
    title: "Pesona King Adham",
    desc: "Jl.Chairil Anwar, THR-Puwatu",
    rating: 4,
    price: "26Jt",
    hargaCoret: "Rp 33.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Pesona King Adham 2",
    linkTiktok: "https://vt.tiktok.com/ZSrxt7wau/",
    linkFacebook: "https://www.facebook.com/share/r/19c7LoTu4B/",
    linkDetail: "/PesonaKingAdham2",
  },
];

export const productTerlaris = [
  {
    image: "/Images/BUMI ANAWAI LAND.jpg",
    title: "Bumi Anawai Land",
    desc: "Jl.Anawai, Kel. Wua-Wua",
    rating: 4,
    price: "4Jt",
    hargaCoret: "Rp 11.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Bumi Anawai Land",
    linkTiktok: "https://vt.tiktok.com/ZSrxtbRbf/",
    linkFacebook: "https://www.facebook.com/AlenkaPropertiKendari/",
    linkDetail: "/BumiAnawaiLand",
  },
  {
    image: "/Images/GRIYA CITRA ANAWAI.jpg",
    title: "Griya Citra Anawai",
    desc: "Jl.Anawai, Kel. Wua-Wua",
    rating: 4,
    price: "6Jt",
    hargaCoret: "Rp 14.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Griya Citra Anawai",
    linkTiktok: "/",
    linkFacebook: "https://www.facebook.com/AlenkaPropertiKendari/",
    linkDetail: "/GriyaCitraAnawai",
  },
  {
    image: "/Images/MUTIARA ATHIRA BARUGA 3.jpg",
    title: "Mutiara Athirah Baruga 3",
    desc: "Jl.Kapten Piere Tendean, Baruga",
    rating: 4,
    price: "46Jt",
    hargaCoret: "Rp 50.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Mutiara Athirah Baruga 3",
    linkTiktok: "https://vt.tiktok.com/ZSrxtb7b2/",
    linkFacebook: "/",
    linkDetail: "/MutiaraAthiraBaruga3",
  },

  {
    image: "/Images/PESONA KING ADHAM 2.jpg",
    title: "Pesona King Adham",
    desc: "Jl.Chairil Anwar, THR-Puwatu",
    rating: 4,
    price: "26Jt",
    hargaCoret: "Rp 33.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Pesona King Adham 2",
    linkTiktok: "https://vt.tiktok.com/ZSrxt7wau/",
    linkFacebook: "/",
    linkDetail: "/PesonaKingAdham2",
  },

  {
    image: "/Images/GRIYA IB HASANAH.jpg",
    title: "Griya IB Hasanah",
    desc: "Jl.Chairil Anwar, THR-Puwatu",
    rating: 4,
    price: "16Jt",
    hargaCoret: "Rp 3.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Griya IB Hasanah",
    linkTiktok: "https://vt.tiktok.com/ZSrQQBgdB/",
    linkFacebook: "https://www.facebook.com/AlenkaPropertiKendari/",
    linkDetail: "/GriyaIbHasanah",
  },

  {
    image: "/Images/MUTIARA ATHIRA BARUGA 2.jpg",
    title: "Mutiara Athirah Baruga 2",
    desc: "Jl.KS Tubun, Baruga",
    rating: 4,
    price: "9Jt",
    hargaCoret: "Rp 26.000.000",
    linkAdmin:
      "https://wa.me/6285242049550?text=Halo, Saya minat perumahan Mutiara Athirah Baruga 2",
    linkTiktok: "/",
    linkFacebook: "/",
    linkDetail: "/MutiaraAthiraBaruga2",
  },
];
